# -*- coding: utf-8 -*-
"""INTL6 Regressão.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ge3VMtOeAJG_64FbjXZUReBnX2Ofopj8
"""

import statsmodels.api as sm
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from statsmodels.formula.api import ols

from google.colab import drive
from google.colab import files
drive.mount ('/content/gdrive', force_remount = True)
dirRaiz = "/content/gdrive/My Drive/"
dirBase = dirRaiz + "Colab Notebooks/"

df = pd.read_csv(dirBase + '01_heights_weights_genders.csv', index_col=0)
df.head(10)

"""Regressão PESO X ALTURA"""

lm = sm.OLS.from_formula('Weight ~ Height', df)
result1 = lm.fit()

print(result1.summary())

fit_reg_log = sm.OLS.from_formula("np.log(Weight) ~ np.log(Height)", df)
result2 = fit_reg_log.fit()
print (result2.summary())

"""O aviso relacionado a "Condition Number" é causado por problemas de escala dos dados. Alterando-se a escala para log-log, contorna-se o problema. Nesta biblioteca, podemos fazer isto dentro da fórmula."""

predicao = result1.predict(df)

heights = df['Height']
weights = df['Weight']
plt.figure(figsize = (8, 8))
plt.plot(heights, weights, '.', mfc = 'white', alpha = .2)
plt.xlabel('Height (in)')
plt.ylabel('Weight (lbs)')
plt.plot(heights, predicao, '-k')

